import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root = path.resolve(import.meta.dirname, '..');
const items = JSON.parse(fs.readFileSync(path.join(root,'assets/library.json'),'utf8'));
const taxonomy = JSON.parse(fs.readFileSync(path.join(root,'assets/taxonomy.json'),'utf8'));
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={photo:'图片',video:'镜头',motion:'动效',audio:'音频',note:'拆解'};
const cards=items.map((item,i)=>`<figure class="shot media-card" data-id="${esc(item.id)}" data-kind="${esc(item.kind)}"><div class="shot-image"><button class="shot-open" type="button" data-open="${esc(item.id)}" aria-label="预览素材：${esc(item.title)}">${item.thumbnail?`<img src="${esc(item.thumbnail)}" alt="${esc(item.title)}" loading="lazy" decoding="async">`:`<div class="note-cover"><strong>拆解笔记 ↗</strong><p>${esc(item.description)}</p></div>`}${['motion','video'].includes(item.kind)?'<span class="cover-play" aria-hidden="true">▶</span>':''}</button><span class="media-type">${label[item.kind]}${item.duration?' / '+esc(item.duration):''}</span><button class="shot-favorite" type="button" data-favorite="${esc(item.id)}" aria-pressed="false" aria-label="收藏：${esc(item.title)}">♡</button></div><figcaption><div><h3>${esc(item.title)}</h3><small>${esc(item.tags.slice(0,3).join(' / '))}</small>${item.isFinal&&item.usedInVideo?`<small class="final-label">${item.approvalStatus==='approved'?'已满意 · ':''}已用最终版</small>`:''}</div><span class="shot-number">${String(i+1).padStart(2,'0')}</span></figcaption>${item.file?`<noscript><a class="fallback-take" href="${esc(item.file)}" download>取用素材 ↓</a></noscript>`:''}</figure>`).join('\n');
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const safeJson=value=>JSON.stringify(value).replaceAll('<','\\u003c');
html=html.replace(/(<div class="gallery" id="gallery"[^>]*>)[\s\S]*?(<\/div>\s*<div[^>]*id="empty")/,(all,start,end)=>start+'\n'+cards+'\n'+end);
html=html.replace(/(<script type="application\/json" id="asset-data">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+safeJson(items)+b);
html=html.replace(/(<script type="application\/json" id="taxonomy-data">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+safeJson(taxonomy)+b);
const revision=crypto.createHash('sha256').update(safeJson({items,taxonomy})).digest('hex').slice(0,12);
html=html.replace(/(<meta name="catalog-version" content=")[^"]+("\s*\/?>)/,'$1'+revision+'$2');
html=html.replace(/(<b id="total-count">)\d+(<\/b>)/,'$1'+items.length+'$2');
html=html.replace(/全部素材 \/ \d+ 个条目/,'全部素材 / '+items.length+' 个条目');
html=html.replace(/(data-type="(all|video|photo|motion|audio|note)"[^>]*>[^<]*(?:<[^>]+>[^<]*<\/[^>]+>[^<]*)?<sup>)\d+(<\/sup>)/g,(all,a,kind,b)=>a+(kind==='all'?items.length:items.filter(i=>i.kind===kind).length)+b);
fs.writeFileSync(path.join(root,'index.html'),html);
console.log(`Catalog built: ${items.length} entries; ${items.filter(i=>i.kind==='motion').length} motions.`);
